### PR TITLE
Add video content parsing (#169)

### PR DESCRIPTION
**Pull request by wbalbo**
Follow the last commits like #173, and created something similar.

I needed to change a bit the PictureHandler.cs class, in the override Create method (to deal now with Audio and Video).

Anything wrong please let me know. I tested with MP4 and AVI files. For AVI files I needed to install a codec pack from this link: https://www.free-codecs.com/k_lite_codec_pack_download.htm?f=k_lite_codec_pack_download (first pack of the list works).

Thanks.

### CODE REVIEW

**Comment by adamshakhabov** [comment]
Good job man!

There is conflict in [PictureHandler.cs](https://github.com/ShapeCrawler/ShapeCrawler/pull/179/conflicts). Please, resolve this.

**Comment by wbalbo** [comment]
Okay, I will get your changes from today and solve in a bit.

**Comment by wbalbo** [comment]
I fixed and made the commit to my branch, look when you can.

Thanks.

**Comment by adamshakhabov** [comment]
[The build is failed]( https://github.com/ShapeCrawler/ShapeCrawler/pull/179/checks?check_run_id=3714150439):

`error CS7036: There is no argument given that corresponds to the required formal parameter 'parentGroupShape' of 'SlideShape.SlideShape(OpenXmlCompositeElement, SCSlide, Shape)'`

**Comment by wbalbo** [comment]
Is a error on constructor, interesting. I will see in a few minutes.

**Comment by wbalbo** [comment]
Fixed.

**Review by adamshakhabov — APPROVED** [review]

**Pull request merged**
