### PR TITLE
Add `AddEmptySlide` overloading methods.

### PR DESCRIPTION
**Pull request by huchim**
:astronaut: Hi @adamshakhabov 

In order to give you a proposal for #508 I created this PR.

```cs
public interface ISlideLayoutType
{
    string Value { get; }
}

public interface ISlideCollection : IReadOnlyList<ISlide>
{
    ISlide AddEmptySlide(ISlideLayout layout);
    ISlide AddEmptySlide(ISlideLayoutType layoutType);
    ISlide AddEmptySlide(string layoutName);
}

public interface ISlideLayout
{
    ISlideLayoutType Type { get; }
}
```

:medal_military: Expected behavior of  `ISlideCollection .AddEmptySlide(ISlideLayoutType)`:

- Add a new slide from "default" layout: `pres.Slides.AddEmptySlide(SCSlideLayoutType.Title)`
- It find first layout in Master Layout
- Copy all placeholders of layout without text content.

:medal_military: Expected behavior of `ISlideCollection .AddEmptySlide(string layoutName)`

- Add a new slide from layout with given name

:medal_military: Expected behavior of `SCSlideLayoutType`

- Initializes a layout type based on [type](https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_ST_SlideLayoutType_topic_ID0EKTIIB.html).

I observed that all layouts types described in the specification are not present in powerpoint file, I don't know if this could be problematic someday  :fortune_cookie:

Thanks

---

## PR-Codex overview
This PR adds a new interface `ISlideLayoutType` and a new class `SCSlideLayoutType` to enumerate all possible slide layout types. It also adds a method to add a new slide by layout type or by layout name.

### Detailed summary
- Adds `ISlideLayoutType` interface
- Adds `SCSlideLayoutType` class to enumerate all possible slide layout types
- Adds `AddEmptySlide(ISlideLayoutType layoutType)` method to add a new slide by layout type
- Adds `AddEmptySlide(string layoutName)` method to add a new slide by layout name

> The following files were skipped due to too many changes: `src/ShapeCrawler/Enums/SCSlideLayoutType.cs`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by adamshakhabov** [comment]
After giving it some thought, I believe we should just provide 9 default layouts, similar to what PowerPoint does:

- Title
- Title and Content
- Section Header
- Two Content
- Comparison
- Title Only
- Blank
- Content with Caption
- Picture with Caption

Both the default and new Slide Masters (`ISlideMaster`) should already include these layouts (`ISlideLayout.Name`), or should be able to create them when a user specifies a name.

So, adding the new method `ISlideCollection.AddEmptySlide(string layoutName)` should be sufficient.

**Comment by huchim** [comment]
The [slide layout](https://learn.microsoft.com/en-us/office/open-xml/working-with-slide-layouts) have a `type` property, but the layout name is defined in their [`CommonSlideData.Name`](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.presentation.commonslidedata.name?view=openxml-2.8.1#documentformat-openxml-presentation-commonslidedata-name).

The enum class `SCSlideLayoutType` provides:

- Title `Title = new("title")`
- Title and Content `TitleAndObject = new("obj");`
- Section Header `SectionHeader = new("secHead");`
- Two Content `TwoObjects = new("twoObj");`
- Comparison 
- Title Only `TitleOnly = new("titleOnly");`
- Blank `Blank = new("blank");`
- Content with Caption `TitleObjectAndCaption = new("objTx")`
- Picture with Caption `PictureAndCaption = new("picTx");`
- *Custom* `PictureAndCaption = new("cust");`
- ...

The `CommonSlideData.Name` is not a constant value, depends on regional culture (maybe), for example in my computer:

*Picture with Caption*

```xml
<p:sldLayout type="picTx" preserve="1">
  <p:cSld name="Imagen con título">
  </p:cSld>
</p:sldLayout>
```

> Both the default and new Slide Masters (ISlideMaster) should already include these layouts (ISlideLayout.Name), or should be able to create them when a user specifies a name.

But on the other hand, presentation created by `SCPresentation.Create();` does have just one layout with no `Name` and `Type` so it's **imposible to create a new layout** by any type or name. To solve this problem, maybe we need to [apply a "theme" to presentation](https://learn.microsoft.com/en-us/office/open-xml/how-to-apply-a-theme-to-a-presentation) from a default file (maybe included in the package assets). Basically, copy the slide master in the "source" presentation to the new presentation. Maybe this could be another issue.

Layouts are dependent of the user presentation, and they should know the name of the layout, `AddEmptySlide(PictureAndCaption)` gives him a shortcut to add an slide without know the display name, but the result could be the expected.

:thinking: As you say, we can remove this overloading and left the `SCSlideLayoutType` for a other PR (:joystick:"*Creates a default slide layout*" `ISlideMaster.AddLayout(SCSlideLayoutType)`)

```diff
public interface ISlideCollection : IReadOnlyList<ISlide>
{
-  ISlide AddEmptySlide(ISlideLayoutType layoutType); 
}
```

Let me know if you are agree with the proposal to remove the overloading method... have a nice day...

:male_detective:

**Comment by adamshakhabov** [comment]
It's all right! I understand your idea now🙂 Let's keep these overloads. 

Could you please add a unit test to verify that the created slide contains placeholders from the layout?

**Comment by huchim** [comment]
Hi!

I added a generic class for "enum classes", this is more easy for me.

```cs
private ISlideLayoutType GetLayoutType()
{
    if (SCSlideLayoutType.TryParse(this.SlideLayoutPart.SlideLayout.Type, out var layoutType))
    {
        return layoutType!;
    }

    return SCSlideLayoutType.Custom;
}

public class SCSlideLayoutType : Enumeration<SCSlideLayoutType>
{
  // ...
}
```

But I just noticed that there is already exists an enumeration `SlideLayoutValues`, and I don't know if this is a problem. Enum classes are more easy to me, because I can add more "info" or methods to a value... anyway, I can remove if you want.

A new test `Add_add_adds_slide_from_layout` was added.

:cowboy_hat_face:

**Review by adamshakhabov — APPROVED** [review]

**Pull request merged**
