### PR TITLE
Slide background fill

### LINKED ISSUE #797: Solid color background fill
Is it possible to set a solid color background fill on a slide? If so, please educate! If not, this issue tracks the need for it.

### PR DESCRIPTION
**Pull request by jcoliz**
Enables a slide to have a (now poorly named) `IShapeFill`.

@ashahabov For your directional review.

Still need to test whether this properly replaces the existing background image setter as expected.

Fixes #797

---

## PR-Codex overview
This PR focuses on enhancing the `Slide` class to support a new `Fill` property for managing slide backgrounds, including solid colors and pictures. It also updates related tests to reflect these changes.

### Detailed summary
- Updated the condition in `ShapeFill.cs` to use `FirstOrDefault()` for safer ancestor retrieval.
- Added a `Fill` property to the `ISlide` interface for slide fill management.
- Removed the `Background` property from `ISlide` and `Slide` classes.
- Implemented the `Fill` property in the `Slide` class to handle fills.
- Updated tests to reflect changes from `Background` to `Fill`, including new tests for setting and getting fill colors and pictures.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jcoliz** [comment]
Ok, this is done. I left the old Background property in there, just marked it as obsolete, in case someone is using it.

**Comment by ashahabov** [comment]
Feel free to remove `ISlide.Background`. I will update the documentation about slide background before the next release.

**Review by ashahabov — APPROVED** [review]

**Comment by ashahabov** [comment]
Feel free to merge if no other changes are expected.

The `master` branch rules were adjusted to allow contributors also to merge after approval.

**Comment by jcoliz** [comment]
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by jcoliz** [comment]
No merge button is shown for me, so I think you still have to do it.

**Pull request merged**
