### PR TITLE
Fix `Memory stream is not expandable`

### PR DESCRIPTION
**Pull request by BiDuang**
## PR-Codex overview
This PR improves the initialization process in `PresentationCore` by allowing the constructor to accept both byte array and stream inputs.

### Detailed summary
- Updated `PresentationCore` constructor to accept both byte array and stream inputs for initializing a PowerPoint presentation.
- Improved memory handling by creating a `MemoryStream` object for byte array input.
- Updated initialization of `sdkPresDocument` using the provided stream.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by ashahabov** [comment]
@BiDuang, thank you for the PR! Please add a Unit test for this fix.

**Comment by BiDuang** [comment]
> @BiDuang, thank you for the PR! Please add a Unit test for this fix.

Well, this feature doesn't required a unit test because it can be easily check by a debugger.

For example, you create a new project (just like #617 code) and add a breakpoint, you will find that the stream's `expandable` now become `true`.

Init a MemoryStream with constructor will make the stream become **NOT** expandable, but create it with no parameter and write the bytes into the stream can slove this problem.

**Comment by ashahabov** [comment]
I mean, if presentation saving throws an exception, then the test can look like this.

```c#
[Test]
public void Save_should_not_throw_exception()
{
    // Arrange
    var pres = new Presentation(StreamOf("some-file.pptx"));
    
    //...

    // Act
    //...
    var act = () => pres.Save();

    // Assert
    act.Should().NotThrow();
}
```

**Comment by BiDuang** [comment]
> I mean, if presentation saving throws an exception, then the test can look like this.
> 
> ```cs
> [Test]
> public void Save_should_not_throw_exception()
> {
>     // Arrange
>     var pres = new Presentation(StreamOf("some-file.pptx"));
>     
>     //...
> 
>     // Act
>     //...
>     var act = () => pres.Save();
> 
>     // Assert
>     act.Should().NotThrow();
> }
> ```

I tried to add some tests and compare the results before and after, but they all passed. I'm confused, but I suspect that the issue (#617) might be caused by the constructor.

Reference: https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream?view=net-8.0#constructors

**Comment by BiDuang** [comment]
Fixed in `17c9e71a88bbc1d7d86d08a780504333bcddfa6c`

**Pull request closed without merging**
