### PR TITLE
Added ability to change the background fill color of a shape

### PR DESCRIPTION
**Pull request by femo1de**
This is a super early implementation but it gets the job done

### CODE REVIEW

**Comment by adamshakhabov** [comment]
Hello @femo1de. Thank you for your PR!

There is `IAutoShape.ShapeFill` class for shape fill behavior. Would be good to add your changes in this level.

Then you can name it `ShapeFill.SetSolidColor()`

**Comment by adamshakhabov** [comment]
@femo1de, did you have time to update PR?

**Comment by femo1de** [comment]
Hi Adam,

sorry I havent had the time yet. I tried adding it to IShapeFill but I found that this would require a lot of refactoring since ShapeFill is used for several types of shapes including images, not all of which who support background colors. Also it doesnt store a reference to the xml element of the ppt. I agree this would have been a better place to add this functionality but unfortunately I havent had the time yet to make these changes.
________________________________

**Comment by adamshakhabov** [comment]
Thank you for the updates.

**Pull request closed without merging**
